[package]

name = "codius-sandbox-core"
version = "0.0.1"
authors = ["Torrie Fischer <torrie@ripple.com>"]

[dependencies.seccomp]

git = "https://github.com/tdfischer/seccomp-rust"

[[bin]]
name = "test"
